package org.db2project.EventDetection.Classifier;

/**
 * This class models one of the clusters identified
 * by the parser in the ouput generated by CLUTO.
 * @author eleal
 *
 */
public class ClutoClusterResult {
	/** The id given by CLUTO to the cluster. */
	private int id;
	
	/** The size of the cluster*/
	private int size;
	
	/** The internal similarity in a cluster */
	private float iSim;
	
	/** The internal standard deviation in a cluster*/
	private float iSDev;
	
	/** The external similarity in a cluster */
	private float eSim;
	
	/** The external standard deviation in a cluster*/
	private float eSDev;
	
	/** Entropy */
	private float entropy;
	
	/** The purity */
	private float purity;
	
	public ClutoClusterResult() {
		// TODO Auto-generated constructor stub
	}

	public ClutoClusterResult(int id, int size, float iSim, float iSDev,
			float eSim, float eSDev, float entropy, float purity) {
		super();
		this.id = id;
		this.size = size;
		this.iSim = iSim;
		this.iSDev = iSDev;
		this.eSim = eSim;
		this.eSDev = eSDev;
		this.entropy = entropy;
		this.purity = purity;
	}

	/* Getters and Setters */
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSize() {
		return size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public float getiSim() {
		return iSim;
	}

	public void setiSim(float iSim) {
		this.iSim = iSim;
	}

	public float getiSDev() {
		return iSDev;
	}

	public void setiSDev(float iSDev) {
		this.iSDev = iSDev;
	}

	public float geteSim() {
		return eSim;
	}

	public void seteSim(float eSim) {
		this.eSim = eSim;
	}

	public float geteSDev() {
		return eSDev;
	}

	public void seteSDev(float eSDev) {
		this.eSDev = eSDev;
	}

	public float getEntropy() {
		return entropy;
	}

	public void setEntropy(float entropy) {
		this.entropy = entropy;
	}

	public float getPurity() {
		return purity;
	}

	public void setPurity(float purity) {
		this.purity = purity;
	}
	
	

}
